# Generated by Django 3.0.8 on 2020-07-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='blogapp.Author')),
            ],
        ),
    ]
