# Generated by Django 3.0.8 on 2020-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20200718_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='E:\\projects\\django\\BlogTime\\BlogTime\\media'),
        ),
    ]
